export const FETCH_RECEIVED_DEALS = "FETCH_RECEIVED_DEALS";
export const FETCH_RECEIVED_DEALS_SUCCESS = "FETCH_RECEIVED_DEALS_SUCCESS";
export const FETCH_RECEIVED_DEALS_FAILURE = "FETCH_RECEIVED_DEALS_FAILURE";

export function fetchReceivedDeals() {
  return {
    type: FETCH_RECEIVED_DEALS,
  };
}
